### ISSUE TITLE
ValueError: Sum of input lengths does not equal the length of the input dataset!

### ISSUE THREAD

**Issue by RuizhiZhu** [BraTS-inpainting/2023_challenge#1]
Hello,
 When I run `train_Pix2Pix3D.py`, I encounter some problems. The error statement is in the following.
<img width="817" alt="截屏2023-06-13 02 27 23" src="https://github.com/BraTS-inpainting/2023_challenge/assets/114100521/cefe5328-fa8a-4782-b629-d6be5bb30cc4">
After consulting the `torch.utils.data.random_split` function, I found that the `lengths` parameter requires a specific number rather than a ratio.
So I made the following changes to the code.
<img width="748" alt="截屏2023-06-13 02 54 49" src="https://github.com/BraTS-inpainting/2023_challenge/assets/114100521/b37f84d3-a0fc-48ed-9b27-9a85b4f0ee7c">
Then the code works fine.
I am not sure if this is a bug?

**Comment by neuronflow** [comment]
Thanks for your interest in our challenge.
@robert-graf @FelixSteinbauer can you please have a look?

**Comment by FelixSteinbauer** [comment]
Hey @RuizhiZhu 
If `train_p` and `val_p` add up to 1.0 ,then the `lengths` parameter is interpreted as **ratio**/fraction of the split (e.g. 80 to 20 for `[0.8, 0.2]`). If they do not add up to 1.0,  `torch.utils.data.random_split` expects the **lengths** of the desired output datasets, which must add up to the length of the input dataset (this is the cause of the original error message). Both ways are valid according to the [official documentation](https://pytorch.org/docs/stable/data.html#torch.utils.data.random_split), so I would not consider this a bug.
Nevertheless, you have to ensure in both scenarios that your `lengths` list either adds up precisely to 1.0 or precisely to the length of the input dataset.

What did you use as  `lengths` that resulted in the above error message?

**Comment by RuizhiZhu** [comment]
Glad to receive your reply！ @FelixSteinbauer 
I didn't make any changes to the code for the above error message.
I compared the official documentation with the local code and I think it's the lower version of my `pytorch` that is causing the problem.The following local code shows that it does not support splitting data using **ratio**.
<img width="865" alt="截屏2023-06-13 17 35 20" src="https://github.com/BraTS-inpainting/2023_challenge/assets/114100521/f13daa4a-498d-4275-8a00-61542528ef39">

**Comment by FelixSteinbauer** [comment]
This seems to be a versioning issue then. Support for ratios in `random_split` was added in [pytroch=1.13](https://pytorch.org/docs/1.13/data.html?highlight=random_split#torch.utils.data.random_split) (compare to [pytroch=1.12](https://pytorch.org/docs/1.12/data.html?highlight=random_split#torch.utils.data.random_split)).

I assume your pytroch version was/is below 1.13 ? (use `pip show torch | grep Version` to check)

In our [environment.yml](https://github.com/BraTS-inpainting/2023_challenge/blob/main/baseline/environment.yml) we specified `pytorch=2.0.0`  (on cuda 11.7). I myself tested with pytorch 2.1.0 and cuda 12.1.
I suppose other participants might run into the same problem though. I will add an comment that references this issue.
