### ISSUE TITLE
Could you release the function "generate_metrics" in inpainting.challenge_metrics_2023 

### ISSUE THREAD

**Issue by siriluo** [BraTS-inpainting/2023_challenge#4]
Hi We want to tackle this challenge and evaluate the metrics on our own, could you release the function "generate_metrics" for evaluation?

**Comment by FelixSteinbauer** [comment]
The code for the `generate_metrics()` function is publicly available in the `inpainting` package @neuronflow has created for this challenge.
You can access the package either on the [respective PyPI Website](https://pypi.org/project/inpainting/) or via `pip install inpainting`. You can simply download the package code under "[Download files](https://pypi.org/project/inpainting/#files)" and extract the archive. Under `inpainting/challenge_metrics_2023.py` you will find the `generate_metrics` function in `line 216` (for package version `0.0.5`)

Does this answer the question?

**Comment by siriluo** [comment]
Thank you!

**Comment by neuronflow** [comment]
this might be helpful, we could consider making this function part of the package:
```

def compute_image_quality_metrics(
    prediction: str,
    healthy_mask: str,
    reference_t1: str,
    voided_t1: str,
) -> dict:
    print("computing metrics!")
    print("prediction:", prediction)
    print("healthy_mask:", healthy_mask)
    print("reference_t1:", reference_t1)
    print("voided_t1:", voided_t1)

    prediction_data = read_nifti_to_tensor(prediction)
    healthy_mask_data = read_nifti_to_tensor(healthy_mask).bool()
    reference_t1_data = read_nifti_to_tensor(reference_t1)
    voided_t1_data = read_nifti_to_tensor(voided_t1)

    metrics = generate_metrics(
        prediction=prediction_data,
        target=reference_t1_data,
        normalization_tensor=voided_t1_data,
        mask=healthy_mask_data,
    )

    return metrics
    
    ```
