### ISSUE TITLE
Questions about BraTS Challenge 2023 Local Synthesis

### ISSUE THREAD

**Issue by siriluo** [BraTS-inpainting/2023_challenge#5]
We participated in this challenge in Aug 2023 and continued our study until recently we have very promising results. Our questions:

The data embargo: we continued our research after the challenge, could we freely publish our methods and results to any journal/conference? 

Any specific restrictions we have to follow, expect the ones listed in this link: https://www.synapse.org/#!Synapse:syn51156910/wiki/622360

Thank you.

**Comment by neuronflow** [comment]
Hi, sorry for not answering your email yet. I was sick in the last few days and there were a few deadlines to take care of. I reserved time to answer your email tomorrow :)
